### PR TITLE
add missing packages to setup instructions

### PR DESCRIPTION
**Pull request by adhintz**
Adds install of pip, pins pip version, and install libav*-dev packages.

Tested on a brand-new install of ubuntu-16.04.5-desktop-amd64.iso

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -33,13 +33,14 @@ Setup
 1. Install native dependencies
 
     - core tools
-        ```
-        sudo apt install git curl
+        ```bash
+        sudo apt install git curl python-pip
+        sudo pip install --upgrade pip==9.0.3
```
Comment (rbiasini) [inline README.md]: Why 9.0.3? if anything, >=9.0.3 (we are on 18.0)

File: README.md [hunk 2]
```diff
@@ -33,13 +33,14 @@ Setup
...
         ```
 
     - ffmpeg (tested with 3.3.2)
         ```bash
-        sudo apt install ffmpeg
+        sudo apt install ffmpeg libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
```
Comment (rbiasini) [inline README.md]: Did you need these packages? actually, the recommended procedure for ubuntu < 18.04 is to compile from source: https://docs.mikeboers.com/pyav/develop/installation.html

File: README.md (hunk 1 above)
Comment (adhintz) [reply README.md]: After upgrading to 18 with sudo pip install --upgrade pip
then I get this error:

    from pip import main
ImportError: cannot import name 'main'

It seems a few other people have had the same issue: https://github.com/pypa/pip/issues/5240#issuecomment-381673100
but I'm guessing there's a better fix if you're using 18.0 on ubuntu 16.04.

File: README.md (hunk 2 above)
Comment (adhintz) [reply README.md]: Without those packages, I get this error: https://github.com/adhintz/openpilot-tools/commit/d83d85a7fd63eb156018384f22dab206ceb163c1

I didn't test if all of them are needed, just copy/pasted the list from someone else that had the same error installing av

File: README.md (hunk 1 above)
Comment (rbiasini) [reply README.md]: `sudo pip install --upgrade pip` works for me, but I cannot manually do `from pip import main` in Python. But yeah, pip should be pinned to a minimum version (`sudo pip install --upgrade pip==18.0`)

File: README.md (hunk 2 above)
Comment (rbiasini) [reply README.md]: ok. I think I've already had some of them installed.
